config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :stocks
  resources :measures
  resources :clotes
  get 'home/index'
  root 'home#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/clote.rb
class Clote < ApplicationRecord
  has_many :stocks
  belongs_to :category
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "120x90#" }, :default_url => "/assets/imageNotAvailable_medium.jpg"
	 do_not_validate_attachment_file_type :photo
  
end

app/controllers/clotes_controller.rb
class ClotesController < ApplicationController
  before_action :set_clote, only: [:show, :edit, :update, :destroy]

  # GET /clotes
  # GET /clotes.json
  def index
    @clotes = Clote.all
  end

  # GET /clotes/1
  # GET /clotes/1.json
  def show
  end

  # GET /clotes/new
  def new
    @clote = Clote.new
  end

  # GET /clotes/1/edit
  def edit
  end

  # POST /clotes
  # POST /clotes.json
  def create
    @clote = Clote.new(clote_params)


    respond_to do |format|
      if @clote.save
        format.html { redirect_to @clote, notice: 'Modelo salvo com sucesso.' }
        format.json { render :show, status: :created, location: @clote }
      else
        format.html { render :new }
        format.json { render json: @clote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clotes/1
  # PATCH/PUT /clotes/1.json
  def update
    respond_to do |format|
      if @clote.update(clote_params)
        format.html { redirect_to @clote, notice: 'Modelo salvo com sucesso.' }
        format.json { render :show, status: :ok, location: @clote }
      else
        format.html { render :edit }
        format.json { render json: @clote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clotes/1
  # DELETE /clotes/1.json
  def destroy
    @clote.destroy
    respond_to do |format|
      format.html { redirect_to clotes_url, notice: ' Modelo excluído.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clote
      @clote = Clote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clote_params
      params.require(:clote).permit(:model, :size, :price, :description, :category_id, :photo)
    end
end

app/helpers/clotes_helper.rb
module ClotesHelper
end

app/views/clotes/_form.html.erb
<%= form_for(@clote, :html => { :multipart => true}) do |f| %>
  <% if @clote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clote.errors.count, "error") %> prohibited this clote from being saved:</h2>

      <ul>
      <% @clote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="field">
    <%= f.label :model, "Modelo" %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :price, "Preço" %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :description, "Descrição" %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
      <%= f.label :category_id, "Categoria" %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= f.label :photo, "Imagem" %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>

</fieldset>
<% end %>

app/views/clotes/edit.html.erb
<% if current_user and current_user.employee == 'y' %>

  <h2>🎀Editar Modelo </h2>

<%= render 'form', clote: @clote %>

<div class="link_back">
  <%= link_to  'Ver', @clote %> |
  <%= link_to  'Voltar', clotes_path %>
</div>
<% else %>
  <p>Acesso Negado</p>
<% end %>

app/views/clotes/index.html.erb
<% if current_user and current_user.employee == 'y' %>

<h2>🎀 Roupas </h2>

<table>
  <thead>
    <tr>
      <th>Imagem</th>
      <th>Categoria</th>
      <th>Modelo</th>
      <th>Preço</th>
      <th>Descrição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clotes.each do |clote| %>
      <tr>
        <td><%= image_tag clote.photo.url(:thumb)%></td>
        <td><%= clote.category.name %></td>
        <td><%= clote.model %></td>
        <td>R$ <%= format("%.2f", clote.price || 0) %></td>
        <td><%= clote.description %></td>
        <td><%= link_to  'Ver', clote %></td>
        <td><%= link_to  'Editar', edit_clote_path(clote) %></td>
        <td><%= link_to  'Excluir', clote, method: :delete, data: { confirm:  'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="link_back">
<%= link_to 'Novo Modelo', new_clote_path %>
</div>
<% else %>
  <p>Acesso Negado</p>
<% end %>

app/views/clotes/new.html.erb
<% if current_user and current_user.employee == 'y' %>
  <h2>🎀 Novo Modelo </h2>

<%= render :partial => 'form' %>
<div class="link_back">
<%= link_to  'Voltar', clotes_path %>
</div>
<% else %>
  <p>Acesso Negado</p>
<% end %>

app/views/clotes/show.html.erb
<% if current_user and current_user.employee == 'y' %>

<h2> 🎀
  <%= @clote.model%>
</h2>

  <figure class="left">
    <%= image_tag @clote.photo.url(:medium)%>
  </figure>
 <br>

  <strong>Modelo:</strong>
  <%= @clote.model %><br>


  <strong>Price:</strong>
    <% if @clote.price %>
      R$ <%= format("%.2f", @clote.price) %>
    <% else %>
      Indisponível
    <% end %><br>
 
  <strong>Descrição:</strong>
  <%= @clote.description %>
 <br>


  <strong>Categoria:</strong>
  <%= @clote.category.name %>
 <br>

<div class="link_back">
<%= link_to  'Editar', edit_clote_path(@clote) %> |
<%= link_to  'Voltar', clotes_path %>
</div>

<% end %>