config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :stocks
  resources :measures
  resources :clotes
  get 'home/index'
  root 'home#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :clotes
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria criada com sucesso.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria excluída.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <div class="field">
    <%= f.label :name, "Categoria" %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "Atualizar" %>
  </div>
</fieldset>
<% end %>

app/views/categories/edit.html.erb
<% if current_user and current_user.employee == 'y' %>
<h2>🎀 Editar Categoria</h2>

<%= render 'form', category: @category %>

<div class="link_back">
<%= link_to 'Ver', @category %> |
<%= link_to 'Voltar', categories_path %>
</div>

<% end %>

app/views/categories/index.html.erb
<% if current_user and current_user.employee == 'y' %>

<h2>🎀 Categorias</h2>

<table>
  <thead>
    <tr>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to  'Ver', category %></td>
        <td><%= link_to  'Editar', edit_category_path(category) %></td>
        <td><%= link_to  'Excluir', category, method: :delete, data: { confirm:  'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="link_back">
<%= link_to 'Nova Categoria', new_category_path %>
</div>
<% end %>

app/views/categories/new.html.erb
<% if current_user and current_user.employee == 'y' %>
  <h2>🎀 Nova Categoria </h2>

<%= render 'form', category: @category %>

<div class="link_back">
<%= link_to  'Voltar', categories_path %>
</div>

<% end %>

app/views/categories/show.html.erb
<% if current_user and current_user.employee == 'y' %>
<p id="notice"><%= notice %></p>

<p>
  <h2>🎀 Categoria</h2>
  <strong>Nome:</strong>
  <%= @category.name %>
</p>

<div class="link_back">
<%= link_to  'Editar', edit_category_path(@category) %> |
<%= link_to  'Voltar', categories_path %>
</div>

<% end %>