config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :stocks
  resources :measures
  resources :clotes
  get 'home/index'
  root 'home#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/measure.rb
class Measure < ApplicationRecord
  has_many :stocks
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_action :set_measure, only: [:show, :edit, :update, :destroy]

  # GET /measures
  # GET /measures.json
  def index
    @measures = Measure.all
  end

  # GET /measures/1
  # GET /measures/1.json
  def show
  end

  # GET /measures/new
  def new
    @measure = Measure.new
  end

  # GET /measures/1/edit
  def edit
  end

  # POST /measures
  # POST /measures.json
  def create
    @measure = Measure.new(measure_params)

    respond_to do |format|
      if @measure.save
        format.html { redirect_to @measure, notice: 'Madida criada com sucesso.' }
        format.json { render :show, status: :created, location: @measure }
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measures/1
  # PATCH/PUT /measures/1.json
  def update
    respond_to do |format|
      if @measure.update(measure_params)
        format.html { redirect_to @measure, notice: 'Medida atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @measure }
      else
        format.html { render :edit }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @measure.destroy
    respond_to do |format|
      format.html { redirect_to measures_url, notice: 'Measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_params
      params.require(:measure).permit(:size, :bust, :waist, :hip)
    end
end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/views/measures/_form.html.erb
<%= form_for(measure) do |f| %>
  <% if measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<fieldset>
  <div class="field">
    <%= f.label :size, "Tamanho" %>
    <%= f.text_field :size %>
  </div>

  <div class="field">
    <%= f.label :bust, "Busto" %>
    <%= f.text_field :bust %>
  </div>

  <div class="field">
    <%= f.label :waist, "Cintura" %>
    <%= f.text_field :waist %>
  </div>

  <div class="field">
    <%= f.label :hip, "Quadril" %>
    <%= f.text_field :hip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/measures/edit.html.erb
<% if current_user and current_user.employee == 'y' %>
  <h2>🎀 Editar Medida </h2>

<%= render 'form', measure: @measure %>

<div class="link_back">
<%= link_to  'Ver', @measure %> |
<%= link_to  'Voltar', measures_path %>
</div>
<% else %>
  <p>Acesso Negado</p>
<% end %>

app/views/measures/index.html.erb
<% if current_user and current_user.employee == 'y' %>

  <h2>🎀 Medidas </h2>

<table>
  <thead>
    <tr>
      <th>Tamanho</th>
      <th>Busto</th>
      <th>Cintura</th>
      <th>Quadril</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measures.each do |measure| %>
      <tr>
        <td><%= measure.size %></td>
        <td><%= measure.bust %></td>
        <td><%= measure.waist %></td>
        <td><%= measure.hip %></td>
        <td><%= link_to  'Ver', measure %></td>
        <td><%= link_to  'Editar', edit_measure_path(measure) %></td>
        <td><%= link_to  'Excluir', measure, method: :delete, data: { confirm:  'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="link_back">
<%= link_to 'Nova Medida', new_measure_path %>
</div>
<% else %>
  <p>Acesso Negado</p>
<% end %>

app/views/measures/new.html.erb
<% if current_user and current_user.employee == 'y' %>
  <h2>🎀 Nova Medida </h2>

<%= render 'form', measure: @measure %>

<div class="link_back">
<%= link_to  'Voltar', measures_path %>
</div>
<% else %>
  <p>Acesso Negado</p>
<% end %>

app/views/measures/show.html.erb
<% if current_user and current_user.employee == 'y' %>

<h2> 🎀 <%= @measure.size %>
</h2>

<p>
  <strong>Tamanho:</strong>
  <%= @measure.size %>
</p>

<p>
  <strong>Busto:</strong>
  <%= @measure.bust %>
</p>

<p>
  <strong>Cintura:</strong>
  <%= @measure.waist %>
</p>

<p>
  <strong>Quadril:</strong>
  <%= @measure.hip %>
</p>

<div class="link_back">
<%= link_to  'Editar', edit_measure_path(@measure) %> |
<%= link_to  'Voltar', measures_path %>
</div>
<% else %>
  <p>Acesso Negado</p>
<% end %>