config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :stocks
  resources :measures
  resources :clotes
  get 'home/index'
  root 'home#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lacos de Seda</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
    <script>
      WebFont.load({
        google: {
          families: ["Cookie:regular"]
        }
      });
    </script>
  </head>

  <body>

  <div class="container-fluid">
     <header class="row">
       <div class="flower">
         <h1 class="left"><%= link_to "Laços de Seda", root_path %></h2>
       <div class="right" style="padding-top:10px;">
         <% if user_signed_in? %>
          <strong><%= current_user.email %></strong>.
           <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %> |
           <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
         <% else %>
           <%= link_to "Cadastrar", new_user_registration_path, :class => 'navbar-link'  %> |
           <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
         <% end %>
       </div>
     </div>
     </header>
     <div class="row">
         <main>
           <div class="flex">
             <div class="set_flex">
               <p class="notice"><%= notice %></p>
               <p class="alert"><%= alert %></p>
             </div>
            <div class="set_flex">
             <% if current_user and current_user.employee == 'y' %>
               <nav class="flex right">

                 <div class="set_flex"><%= link_to 'Categorias', categories_path %></div>
                 <div class="set_flex"><%= link_to 'Modelos', clotes_path %></div>
                 <div class="set_flex"><%= link_to 'Estoque', stocks_path %></div>
                 <div class="set_flex"><%= link_to 'Medidas', measures_path %></div>
               </nav>
              <% end %>
            </div>
        </div>
           <%= yield %>
         </main>
     </div>
     <footer class="row">
      <div class="flower">
      </div>
     </footer>
  </div>
  </body>
</html>